APP_OPTIM := debug
APP_PLATFORM := android-9
APP_STL := stlport_static
APP_CPPFLAGS += -DANDROID
APP_CPPFLAGS += -DENGINE_EXPORTS
APP_CPPFLAGS += -DENGINE_STATIC_LIB
APP_ABI := armeabi armeabi-v7a
APP_MODULES := engine
